### ISSUE TITLE
为什么会有'cannot open resource'报错

### ISSUE THREAD

**Issue by xiaoxianyu233** [AkiraXie/hoshino.nb2#4]
报错如下：

04-10 18:28:15 [WARNING] hoshino | static\img is not a directory and a file!
if img.* or *.img is file or dir,please use + or () opearator.
04-10 18:28:15 [ERROR] nonebot | Failed to import "zai"
Traceback (most recent call last):
  File "C:\sb\HoshinoBot\run.py", line 24, in <module>
    nonebot.load_plugins(base)
  File "C:\sb\HoshinoBot\venv\lib\site-packages\nonebot\plugin\load.py", line 39, in load_plugins
    return manager.load_all_plugins()
  File "C:\sb\HoshinoBot\venv\lib\site-packages\nonebot\plugin\manager.py", line 128, in load_all_plugins
    return set(
  File "C:\sb\HoshinoBot\venv\lib\site-packages\nonebot\plugin\manager.py", line 129, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.list_plugins()))
> File "C:\sb\HoshinoBot\venv\lib\site-packages\nonebot\plugin\manager.py", line 106, in load_plugin
    module = importlib.import_module(
  File "C:\sb\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\sb\HoshinoBot\hoshino\__init__.py", line 192, in <module>
    from .service import Service
  File "C:\sb\HoshinoBot\hoshino\service.py", line 29, in <module>
    from hoshino.util import _strip_cmd
  File "C:\sb\HoshinoBot\hoshino\util\__init__.py", line 40, in <module>
    DEFAULTFONT = ImageFont.truetype(
  File "C:\sb\HoshinoBot\venv\lib\site-packages\PIL\ImageFont.py", line 878, in truetype
    return freetype(font)
  File "C:\sb\HoshinoBot\venv\lib\site-packages\PIL\ImageFont.py", line 875, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "C:\sb\HoshinoBot\venv\lib\site-packages\PIL\ImageFont.py", line 226, in __init__
    self.font = core.getfont(
OSError: cannot open resource

如果是缺少图片，但是我没有图片怎么解决，base目录下的文件都有这个报错

**Comment by SEAFHMC** [comment]
看看你有没有
STATIC/img/priconne/gadget/SourceHanSans-Regular.ttc

**Comment by Cathgao** [comment]
同样的报错，static文件夹是空的
